class Receipe {
    constructor(name, category, sellsFor, energy, ingredients, stars)   {
        this.name = name;
        this.category = category;
        this.sellsFor = sellsFor;
        this.energy = energy;
        this.ingredients = ingredients.map((x) => x);
        this.stars = stars;
    }

    receipeCost() {
        
        let cost = null;
        console.log(this.ingredients)
        
        for(let i=0; i<(this.ingredients.length); i++) {

            console.log(this.ingredients[i]);
            let x = allIngredients.find(e => (e.name === this.ingredients[i]))
            console.log(x)
            //console.log(allIngredients[]);

            cost = cost + x.seedPrice;
        }
        return cost; 
        
       
      

    }

    receipeProfit() {
        return (this.sellsFor - this.receipeCost())
    }

}

class Ingredient    {
    constructor(name, category, buyPrice, seedPrice, sellPrice, energy, growTime, water, amount, location, sources) {
        this.name = name;
        this.category = category;
        this.buyPrice = buyPrice;
        this.seedPrice = seedPrice;
        this.sellPrice = sellPrice;
        this.energy = energy;
        this.growTime = growTime;
        this.water = water;
        this.amount = amount;
        this.location = location;
        this.sources = sources;
        
        //this.location = location.slice();
        //this.sources = sources.slice();
        this.location = location.map((x) => x);
        this.sources = sources.map((x) => x);
    }

    printIngredientsProfit() {
        let profit = null;
        profit = this.sellPrice - this.buyPrice;
        console.log(profit)

    } 

    printIngredientGrowProfit() {

        let profit = null;
        profit = this.sellPrice - this.seedPrice;
        console.log(profit)

    }
    
    IngredientsProfit() {
        let profit = null;
        profit = this.sellPrice - this.buyPrice;
        return profit;

    } 

    IngredientGrowProfit() {

        let profit = null;
        profit = this.sellPrice - this.seedPrice;
        return profit;

    }

}

let ingredientJSON = `[
    {
      "Image": null,
      "Name": null,
      "Cooking": "Category",
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Asparagus",
      "Cooking": " Vegetables",
      "Buy Price": " 200",
      "Sell Price": 133,
      "Energy": 42,
      "Grow Time": " 2 h 15 m",
      "Water": "2",
      "Yield": "3",
      "Location": " Frosted Heights",
      "Sources": " Asparagus Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Bell Pepper",
      "Cooking": " Vegetables",
      "Buy Price": " 50",
      "Sell Price": 33,
      "Energy": 79,
      "Grow Time": " 15 m",
      "Water": "1",
      "Yield": "1",
      "Location": " Forest of Valor",
      "Sources": " Bell Pepper Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Carrot",
      "Cooking": " Vegetables",
      "Buy Price": " 66",
      "Sell Price": 44,
      "Energy": 57,
      "Grow Time": " 15 m",
      "Water": "1",
      "Yield": "1",
      "Location": " Peaceful Meadow",
      "Sources": " Carrot Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Chili Pepper",
      "Cooking": " Vegetables",
      "Buy Price": " 117",
      "Sell Price": 78,
      "Energy": 140,
      "Grow Time": " 45 m",
      "Water": "1",
      "Yield": "1",
      "Location": " Sunlit Plateau",
      "Sources": " Chili Pepper Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Corn",
      "Cooking": " Vegetables",
      "Buy Price": " 24",
      "Sell Price": 16,
      "Energy": 30,
      "Grow Time": " 12 m",
      "Water": "1",
      "Yield": "2",
      "Location": " Dazzle Beach",
      "Sources": " Corn Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Cucumber",
      "Cooking": " Vegetables",
      "Buy Price": " 239",
      "Sell Price": 159,
      "Energy": 145,
      "Grow Time": " 1 h 15 m",
      "Water": "1",
      "Yield": "1",
      "Location": " Frosted Heights",
      "Sources": " Cucumber Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Eggplant",
      "Cooking": " Vegetables",
      "Buy Price": " 462",
      "Sell Price": 308,
      "Energy": 451,
      "Grow Time": " 3 h",
      "Water": "2",
      "Yield": "1",
      "Location": " Frosted Heights",
      "Sources": " Eggplant Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Leek",
      "Cooking": " Vegetables",
      "Buy Price": " 464",
      "Sell Price": 309,
      "Energy": 228,
      "Grow Time": " 2 h",
      "Water": "2",
      "Yield": "1",
      "Location": " Forgotten Lands",
      "Sources": " Leek Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Lettuce",
      "Cooking": " Vegetables",
      "Buy Price": " 12",
      "Sell Price": 8,
      "Energy": 56,
      "Grow Time": " 3 m",
      "Water": "1",
      "Yield": "1",
      "Location": " Peaceful Meadow",
      "Sources": " Lettuce Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Mushroom",
      "Cooking": " Vegetables",
      "Buy Price": "n/a",
      "Sell Price": 30,
      "Energy": 105,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "10 (max spawn)",
      "Location": " Glade of Trust",
      "Sources": " Foraging"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Okra",
      "Cooking": " Vegetables",
      "Buy Price": " 171",
      "Sell Price": 114,
      "Energy": 31,
      "Grow Time": " 2 h",
      "Water": "1",
      "Yield": "3",
      "Location": " Glade of Trust",
      "Sources": " Okra Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Onion",
      "Cooking": " Vegetables",
      "Buy Price": " 255",
      "Sell Price": 170,
      "Energy": 146,
      "Grow Time": " 1 h 15 m",
      "Water": "2",
      "Yield": "1",
      "Location": " Forest of Valor",
      "Sources": " Onion Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Potato",
      "Cooking": " Vegetables",
      "Buy Price": " 189",
      "Sell Price": 126,
      "Energy": 113,
      "Grow Time": " 35 m",
      "Water": "3",
      "Yield": "1",
      "Location": " Forgotten Lands",
      "Sources": " Potato Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Pumpkin",
      "Cooking": " Vegetables",
      "Buy Price": " 996",
      "Sell Price": 664,
      "Energy": 187,
      "Grow Time": " 4 h",
      "Water": "2",
      "Yield": "1",
      "Location": " Forgotten Lands",
      "Sources": " Pumpkin Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Spinach",
      "Cooking": " Vegetables",
      "Buy Price": " 62",
      "Sell Price": 41,
      "Energy": 60,
      "Grow Time": " 1 h",
      "Water": "2",
      "Yield": "3",
      "Location": " Glade of Trust",
      "Sources": " Spinach Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Tomato",
      "Cooking": " Vegetables",
      "Buy Price": " 33",
      "Sell Price": 22,
      "Energy": 21,
      "Grow Time": " 25 m",
      "Water": "2",
      "Yield": "3",
      "Location": " Dazzle Beach",
      "Sources": " Tomato Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Zucchini",
      "Cooking": " Vegetables",
      "Buy Price": " 78",
      "Sell Price": 52,
      "Energy": 48,
      "Grow Time": " 40 m",
      "Water": "2",
      "Yield": "2",
      "Location": " Sunlit Plateau",
      "Sources": " Zucchini Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Apple",
      "Cooking": " Fruit",
      "Buy Price": " 50",
      "Sell Price": 25,
      "Energy": 300,
      "Grow Time": " 20 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Apple Tree:",
      "Sources": " Goofy's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Forgotten Lands",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Plaza",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Banana",
      "Cooking": " Fruit",
      "Buy Price": " 58",
      "Sell Price": 29,
      "Energy": 350,
      "Grow Time": " 23 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Banana Tree:",
      "Sources": " Goofy's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Peaceful Meadow",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Dazzle Beach",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Moana Realm",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Blueberry",
      "Cooking": " Fruit",
      "Buy Price": " 58",
      "Sell Price": 29,
      "Energy": 350,
      "Grow Time": " 23 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Blueberry Bush:",
      "Sources": " Goofy's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Forest of Valor",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Dazzle Beach",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Cherry",
      "Cooking": " Fruit",
      "Buy Price": " 83",
      "Sell Price": 42,
      "Energy": 500,
      "Grow Time": " 33 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Cherry Tree:",
      "Sources": " Goofy's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Frosted Heights",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Sunlit Plateau",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Coconut",
      "Cooking": " Fruit",
      "Buy Price": "n/a",
      "Sell Price": 42,
      "Energy": 500,
      "Grow Time": " 23 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Coconut Tree:",
      "Sources": "After  Burying the Eel "
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Dazzle Beach",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Moana Realm",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Coffee Bean",
      "Cooking": " Fruit",
      "Buy Price": "n/a",
      "Sell Price": 36,
      "Energy": 425,
      "Grow Time": " 40 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Coffee Bush:",
      "Sources": "After  Very Sleepy Stitch "
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Glade of Trust",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Dreamlight Fruit",
      "Cooking": " Fruit",
      "Buy Price": "n/a",
      "Sell Price": 40,
      "Energy": 500,
      "Grow Time": " 1 d",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Dreamlight Tree:",
      "Sources": "After  Seed of Memories "
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Sunlit Plateau",
      "Sources": null
    },
    {
      "Image": " Dreamlight Tree:",
      "Name": "After  The Dreamlight Grove ",
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "   ",
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": " Glade of Trust",
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "   ",
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": " Frosted Heights",
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "   ",
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": " Forgotten Lands",
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Gooseberry",
      "Cooking": " Fruit",
      "Buy Price": " 100",
      "Sell Price": 50,
      "Energy": 600,
      "Grow Time": " 40 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Gooseberry Bush:",
      "Sources": " Goofy's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Frosted Heights",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Forgotten Lands",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Lemon",
      "Cooking": " Fruit",
      "Buy Price": " 67",
      "Sell Price": 33,
      "Energy": 400,
      "Grow Time": " 27 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Lemon Tree:",
      "Sources": " Goofy's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Forest of Valor",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Glade of Trust",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Raspberry",
      "Cooking": " Fruit",
      "Buy Price": "n/a",
      "Sell Price": 21,
      "Energy": 275,
      "Grow Time": " 17 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Raspberry Bush:",
      "Sources": " Goofy's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Plaza",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Peaceful Meadow",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Rice",
      "Cooking": " Grains",
      "Buy Price": " 92",
      "Sell Price": 61,
      "Energy": 59,
      "Grow Time": " 50 m",
      "Water": "2",
      "Yield": "2",
      "Location": " Glade of Trust",
      "Sources": " Rice Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Wheat",
      "Cooking": " Grains",
      "Buy Price": " 3",
      "Sell Price": 2,
      "Energy": 19,
      "Grow Time": " 1 m",
      "Water": "1",
      "Yield": "2",
      "Location": " Peaceful Meadow",
      "Sources": " Wheat Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Butter",
      "Cooking": " Dairy and Oil",
      "Buy Price": " 190",
      "Sell Price": 190,
      "Energy": 285,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "n/a",
      "Location": " Chez Remy",
      "Sources": "After  A Restaurant Makeover "
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Canola",
      "Cooking": " Dairy and Oil",
      "Buy Price": " 164",
      "Sell Price": 109,
      "Energy": 59,
      "Grow Time": " 35 m",
      "Water": "3",
      "Yield": "1",
      "Location": " Forest of Valor",
      "Sources": " Canola Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Cheese",
      "Cooking": " Dairy and Oil",
      "Buy Price": " 180",
      "Sell Price": 180,
      "Energy": 270,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "n/a",
      "Location": " Chez Remy",
      "Sources": "After  A Restaurant Makeover "
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Egg",
      "Cooking": " Dairy and Oil",
      "Buy Price": " 220",
      "Sell Price": 220,
      "Energy": 330,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "n/a",
      "Location": " Chez Remy",
      "Sources": "After  A Restaurant Makeover "
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Milk",
      "Cooking": " Dairy and Oil",
      "Buy Price": " 230",
      "Sell Price": 230,
      "Energy": 345,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "n/a",
      "Location": " Chez Remy",
      "Sources": "After  A Restaurant Makeover "
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Peanut",
      "Cooking": " Dairy and Oil",
      "Buy Price": " 200",
      "Sell Price": 200,
      "Energy": 300,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "n/a",
      "Location": " Chez Remy",
      "Sources": "After  Remy's Recipe Book "
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Soya",
      "Cooking": " Dairy and Oil",
      "Buy Price": " 104",
      "Sell Price": 69,
      "Energy": 58,
      "Grow Time": " 1 h 30 m",
      "Water": "2",
      "Yield": "3",
      "Location": " Sunlit Plateau",
      "Sources": " Soya Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Basil",
      "Cooking": " Spices",
      "Buy Price": "n/a",
      "Sell Price": 50,
      "Energy": 100,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "10 (max spawn)",
      "Location": " Peaceful Meadow",
      "Sources": " Foraging"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Garlic",
      "Cooking": " Spices",
      "Buy Price": "n/a",
      "Sell Price": 50,
      "Energy": 135,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "10 (max spawn)",
      "Location": " Forest of Valor",
      "Sources": " Foraging"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Ginger",
      "Cooking": " Spices",
      "Buy Price": "n/a",
      "Sell Price": 50,
      "Energy": 175,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "10 (max spawn)",
      "Location": " Forgotten Lands",
      "Sources": " Foraging"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Mint",
      "Cooking": " Spices",
      "Buy Price": "n/a",
      "Sell Price": 50,
      "Energy": 155,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "10 (max spawn)",
      "Location": " Frosted Heights",
      "Sources": " Foraging"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Oregano",
      "Cooking": " Spices",
      "Buy Price": "n/a",
      "Sell Price": 50,
      "Energy": 95,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "10 (max spawn)",
      "Location": " Plaza",
      "Sources": " Foraging"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Cocoa Bean",
      "Cooking": " Sweets",
      "Buy Price": " 75",
      "Sell Price": 38,
      "Energy": 450,
      "Grow Time": " 30 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Cacao Tree:",
      "Sources": " Goofy's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Sunlit Plateau",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": "   ",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Glade of Trust",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Sugarcane",
      "Cooking": " Sweets",
      "Buy Price": " 29",
      "Sell Price": 19,
      "Energy": 46,
      "Grow Time": " 7 m",
      "Water": "1",
      "Yield": "1",
      "Location": " Dazzle Beach",
      "Sources": " Sugarcane Seed"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": " Goofy's Stall"
    },
    {
      "Image": "Picture",
      "Name": "Vanilla",
      "Cooking": " Sweets",
      "Buy Price": "n/a",
      "Sell Price": 50,
      "Energy": 135,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "10 (max spawn)",
      "Location": " Sunlit Plateau",
      "Sources": " Foraging"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Slush Ice",
      "Cooking": " Ice",
      "Buy Price": " 150",
      "Sell Price": 150,
      "Energy": 225,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "n/a",
      "Location": " Chez Remy",
      "Sources": "After  The Unknown Flavor "
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Clam",
      "Cooking": " Seafood",
      "Buy Price": "n/a",
      "Sell Price": 50,
      "Energy": 120,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "5 (max spawn)",
      "Location": " Dazzle Beach",
      "Sources": " Foraging"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Oyster",
      "Cooking": " Seafood",
      "Buy Price": "n/a",
      "Sell Price": 50,
      "Energy": 250,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "4 (max spawn)",
      "Location": " Dazzle Beach",
      "Sources": " Foraging"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Scallop",
      "Cooking": " Seafood",
      "Buy Price": "n/a",
      "Sell Price": 50,
      "Energy": 125,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "4 (max spawn)",
      "Location": " Dazzle Beach",
      "Sources": " Foraging"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Bamboo",
      "Cooking": " Vegetables",
      "Buy Price": null,
      "Sell Price": 80,
      "Energy": 155,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": " Wild Tangle",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Beans",
      "Cooking": " Vegetables",
      "Buy Price": null,
      "Sell Price": 49,
      "Energy": 41,
      "Grow Time": " 1 h",
      "Water": null,
      "Yield": "3",
      "Location": " Glittering Dunes",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Broccoli",
      "Cooking": " Vegetables",
      "Buy Price": null,
      "Sell Price": 152,
      "Energy": 73,
      "Grow Time": " 40 m",
      "Water": null,
      "Yield": "1",
      "Location": " Glittering Dunes",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Cabbage",
      "Cooking": " Vegetables",
      "Buy Price": null,
      "Sell Price": 256,
      "Energy": 142,
      "Grow Time": " 1 h",
      "Water": null,
      "Yield": "1",
      "Location": " Wild Tangle",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Celery",
      "Cooking": " Vegetables",
      "Buy Price": null,
      "Sell Price": 65,
      "Energy": 60,
      "Grow Time": " 10 m",
      "Water": null,
      "Yield": "1",
      "Location": " Ancient's Landing",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Flute Root",
      "Cooking": " Vegetables",
      "Buy Price": null,
      "Sell Price": 112,
      "Energy": 46,
      "Grow Time": " 10 m",
      "Water": null,
      "Yield": "2",
      "Location": " Ancient's Landing",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Ruby Lentils",
      "Cooking": " Vegetables",
      "Buy Price": null,
      "Sell Price": 156,
      "Energy": 37,
      "Grow Time": " 2 h",
      "Water": null,
      "Yield": "3",
      "Location": " Wild Tangle",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Turnip",
      "Cooking": " Vegetables",
      "Buy Price": null,
      "Sell Price": 187,
      "Energy": 263,
      "Grow Time": " 4 h",
      "Water": null,
      "Yield": "2",
      "Location": " Wild Tangle",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Yam",
      "Cooking": " Vegetables",
      "Buy Price": null,
      "Sell Price": 36,
      "Energy": 83,
      "Grow Time": " 4 h",
      "Water": null,
      "Yield": "1",
      "Location": " Ancient's Landing",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Almonds",
      "Cooking": " Fruit",
      "Buy Price": null,
      "Sell Price": 42,
      "Energy": 500,
      "Grow Time": " 50 m",
      "Water": "n/a",
      "Yield": "2",
      "Location": " Wild Tangle",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Cactoberries",
      "Cooking": " Fruit",
      "Buy Price": null,
      "Sell Price": 34,
      "Energy": 400,
      "Grow Time": " 45 m",
      "Water": "n/a",
      "Yield": "2",
      "Location": " Glittering Dunes",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Cosmic Figs",
      "Cooking": " Fruit",
      "Buy Price": null,
      "Sell Price": 22,
      "Energy": 52,
      "Grow Time": " 25 m",
      "Water": "n/a",
      "Yield": "2",
      "Location": " Ancient's Landing",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Dates",
      "Cooking": " Fruit",
      "Buy Price": null,
      "Sell Price": 29,
      "Energy": 350,
      "Grow Time": " 55 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Glittering Dunes",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Dreamango",
      "Cooking": " Fruit",
      "Buy Price": null,
      "Sell Price": 50,
      "Energy": 600,
      "Grow Time": " 1 h",
      "Water": "n/a",
      "Yield": "2",
      "Location": " Wild Tangle",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Grapes",
      "Cooking": " Fruit",
      "Buy Price": null,
      "Sell Price": 9,
      "Energy": 21,
      "Grow Time": " 20 m",
      "Water": "n/a",
      "Yield": "3",
      "Location": " Ancient's Landing",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Melon",
      "Cooking": " Fruit",
      "Buy Price": null,
      "Sell Price": 93,
      "Energy": 88,
      "Grow Time": " 30 m",
      "Water": "n/a",
      "Yield": "1",
      "Location": " Glittering Dunes",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Nestling Pear",
      "Cooking": " Fruit",
      "Buy Price": null,
      "Sell Price": 25,
      "Energy": 300,
      "Grow Time": " 35 m",
      "Water": "n/a",
      "Yield": "2",
      "Location": " Ancient's Landing",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Pineapple",
      "Cooking": " Fruit",
      "Buy Price": null,
      "Sell Price": 532,
      "Energy": 168,
      "Grow Time": " 3 h",
      "Water": "n/a",
      "Yield": "1",
      "Location": " Wild Tangle",
      "Sources": null
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Strawberry",
      "Cooking": " Fruit",
      "Buy Price": null,
      "Sell Price": 23,
      "Energy": 275,
      "Grow Time": " 30 m",
      "Water": "n/a",
      "Yield": "2",
      "Location": " Ancient's Landing",
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Pork",
      "Cooking": " Protein",
      "Buy Price": " 250",
      "Sell Price": 250,
      "Energy": 250,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "n/a",
      "Location": " Glittering Dunes",
      "Sources": "Gaston's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Poultry",
      "Cooking": " Protein",
      "Buy Price": " 500",
      "Sell Price": 500,
      "Energy": 250,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "n/a",
      "Location": " Glittering Dunes",
      "Sources": "Gaston's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Venison",
      "Cooking": " Protein",
      "Buy Price": " 1,000",
      "Sell Price": 500,
      "Energy": 250,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": "n/a",
      "Location": " Glittering Dunes",
      "Sources": "Gaston's Stall"
    },
    {
      "Image": null,
      "Name": null,
      "Cooking": null,
      "Buy Price": null,
      "Sell Price": null,
      "Energy": null,
      "Grow Time": null,
      "Water": null,
      "Yield": null,
      "Location": null,
      "Sources": null
    },
    {
      "Image": "Picture",
      "Name": "Agave",
      "Cooking": " Sweets",
      "Buy Price": "n/a",
      "Sell Price": 25,
      "Energy": 100,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": null,
      "Location": " Glittering Dunes",
      "Sources": " Foraging"
    },
    {
      "Image": "Picture",
      "Name": "Cinnamon",
      "Cooking": " Spices",
      "Buy Price": "n/a",
      "Sell Price": 30,
      "Energy": 155,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": null,
      "Location": " Wild Tangle",
      "Sources": " Foraging"
    },
    {
      "Image": "Picture",
      "Name": "Cumin",
      "Cooking": " Spices",
      "Buy Price": "n/a",
      "Sell Price": 15,
      "Energy": 90,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": null,
      "Location": " Ancient's Landing",
      "Sources": " Foraging"
    },
    {
      "Image": "Picture",
      "Name": "Majestea",
      "Cooking": " Spices",
      "Buy Price": "n/a",
      "Sell Price": 30,
      "Energy": 105,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": null,
      "Location": " Ancient's Landing",
      "Sources": " Foraging"
    },
    {
      "Image": "Picture",
      "Name": "Paprika",
      "Cooking": " Spices",
      "Buy Price": "n/a",
      "Sell Price": 50,
      "Energy": 125,
      "Grow Time": "n/a",
      "Water": "n/a",
      "Yield": null,
      "Location": " Glittering Dunes",
      "Sources": " Foraging"
    }
   ]`  ;

let ingredientList = JSON.parse(ingredientJSON);   



let ing1 = new Ingredient("Asparagus", "Vegetables", 200, 150, 133, 42, 135, 2, 3, ["Forsted Heights"], ["Asparagus Seed", "Goofy's Stall"]);
let ing2 = new Ingredient("Canola", "Dairy and Oil", 164, 25, 109,59,35,3,1,["Forest of Valor"], ["Canola Seed", "Goofy's Stall"]  )
let allIngredients = [ing1, ing2];

console.log(`Hello Bobbie`);
console.log(allIngredients);


console.log(ing1);
//ing1.printIngredientsProfit()             Test Print
//ing1.printIngredientGrowProfit()          Test Print
console.log(`${ing1.IngredientGrowProfit()}`)
console.log(`${ing1.IngredientsProfit()}`)

console.log(ing2);
//ing2.printIngredientsProfit();
//ing2.printIngredientGrowProfit()
console.log(`${ing2.IngredientGrowProfit()}`)
console.log(`${ing2.IngredientsProfit()}`)

let rec1 = new Receipe("Roasted Asparagus", "Appetizer", 313, 221, ["Asparagus", "Canola"], 2 );
console.log(rec1);
console.log(`${rec1.receipeCost()}`);
console.log(`${rec1.receipeProfit()}`);
console.log(ingredientList);
console.log(ingredientList[1].Name);
//console.log(ingredientList[1].Buy);